version: "3.8"

services:
  fonts-upset-dev:
    image: ghcr.io/fransallen/fonts.upset.dev:latest
    environment:
      - FONTS_LOG
      - POP_ID
    networks:
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true

        # HTTPS router
        - traefik.http.routers.fonts-upset-dev-secure.rule=Host(`fonts.upset.dev`)
        - traefik.http.routers.fonts-upset-dev-secure.entrypoints=websecure
        - traefik.http.routers.fonts-upset-dev-secure.tls=true
        - traefik.http.routers.fonts-upset-dev-secure.service=fonts-upset-dev

        # HTTP router (serves real traffic)
        - traefik.http.routers.fonts-upset-dev.rule=Host(`fonts.upset.dev`)
        - traefik.http.routers.fonts-upset-dev.entrypoints=web
        - traefik.http.routers.fonts-upset-dev.service=fonts-upset-dev

        # Service
        - traefik.http.services.fonts-upset-dev.loadbalancer.server.port=8080
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traefik-public:
    external: true
